// Auto generated header
// Copyright (c) 2005-2017 by Juphoon System Software, Inc. All rights reserved.

#include "mtc/mtc.h"
#include "mtc/mtc_call.h"
#include "mtc/mtc_call_ext.h"
#include "mtc/mtc_cc.h"
#include "mtc/mtc_conf.h"
#include "mtc/mtc_conf_db.h"
#include "mtc/mtc_conf2.h"
#include "mtc/mtc_doodle.h"
#include "mtc/mtc_d0.h"
#include "mtc/mtc_d2.h"
#include "mtc/mtc_diag.h"
#include "mtc/mtc_wgw.h"
#include "mtc/mtc_sgw.h"
#include "mtc/mtc_push.h"
#include "mtc/mtc_path.h"
#include "mtc/mtc_conn.h"
#include "mtc/mtc_fs.h"
#include "mtc/mtc_fs2.h"
#include "mtc/mtc_fs_db.h"
#include "mtc/mtc_game.h"
#include "mtc/mtc_point.h"
#include "mtc/mtc_rdcall.h"
#include "mtc/mtc_payment.h"
#include "mtc/mtc_contact.h"
#include "mtc/mtc_buddy.h"
#include "mtc/mtc_group.h"
#include "mtc/mtc_im.h"
#include "mtc/mtc_im_db.h"
#include "mtc/mtc_media.h"
